table People
	lineageTag: ca807b1c-dfc9-41ca-8158-bcafb70a53a8

	column Person
		dataType: string
		lineageTag: 8625ea39-a017-4a96-83b1-31fbc603605b
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c658dea8-0a2b-4ea2-a410-116c8bc02efd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition People = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Qtech\Downloads\Sample - Superstore (1).xls"), null, true),
				    People1 = Source{[Name="People"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People1,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

