table Orders
	lineageTag: 0f04ff8d-63b1-4c09-b24c-3fa38e860261

	measure 'Avg. Purchase Frequency' = COUNT(Orders[Row ID])/DISTINCTCOUNT(Orders[Customer ID])
		lineageTag: 3d57da3b-bda3-405d-8e18-ceea6db05fc1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Revenue Per User' = SUM(Orders[Sales])/DISTINCTCOUNT(Orders[Customer ID])
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 77e2daba-5136-4dc3-a7e6-14d367acff45

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Previous YTD' = [Total Sales]-CALCULATE(SUM(Orders[Sales]), DATEADD(Orders[Order Date].[Date],-1,YEAR))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a4f1f58a-04bf-42bc-a436-c2d9103c6d3f

	measure 'Total Sales' = SUM(Orders[Sales])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5776a9e6-ae37-426d-b798-76256329fe9d

	measure 'New Measure Change' = "Hello World"
		lineageTag: 1f942d5c-bc2f-4e4b-9b0a-499bff5a5e70

	column 'Row ID'
		dataType: string
		lineageTag: f6cd7f63-9622-46c9-91a2-e132e43e498a
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 41968fef-5783-4079-82f7-fe721eae5c1e
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fdb22021-3059-4017-8986-45d44940232b
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 595d06f0-2a05-42da-8c8f-3503b213f08a
			defaultHierarchy: LocalDateTable_bc16b94d-f40a-4b8b-aeff-9537e5d165b5.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09b7175d-8095-4e0b-b34f-262fc41a250b
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 04dd9e33-ec99-4b09-87c6-b5ac160bdf13
			defaultHierarchy: LocalDateTable_9bf06c3b-1a79-4bc3-8c25-4e05a2a98845.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: dee48ce3-db7b-4fed-abf1-9da62627bafa
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: ce5865db-7576-4143-84a6-5da4d829e106
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: f66ad62e-630c-4cd9-b3b3-583095249cf8
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 577acdea-0922-4b75-9244-ad52badf917b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: fb322772-c20f-4f23-a889-993064c3e8d1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1bd2a434-43c7-4bb5-886e-2bc7479dbf27
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e214c9fb-7a2d-48eb-b61f-602888bd1ff5
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 9b6b8b4d-b5e1-45aa-90ad-8863e13d2a78
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 49125765-7b48-4054-b9d1-5be48bff953d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: ff368401-1eed-450f-b69d-24ca41c92eb0
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 079bfa67-24c9-4583-b841-3d1a6dd0730e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 9b1f38e2-fe23-41e2-96bc-8806b8b90dfe
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a27a34e5-0be1-43a4-9eb1-3d4423c866d7
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: fb1c3493-514e-48ec-a3e3-ed19ebefe392
		summarizeBy: sum
		sourceColumn: Sales

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: double
		lineageTag: f1792bca-3663-46a8-b3b8-611982eaa4ff
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: string
		lineageTag: c31a7879-4bc2-456d-9e7f-152296c519b7
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: 3355db16-c501-4cc9-9345-c7e83e7efa8c
		summarizeBy: sum
		sourceColumn: Profit

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duration for delivery' = DATEDIFF(Orders[Order Date],Orders[Ship Date],DAY)
		dataType: int64
		formatString: 0
		lineageTag: 8c400413-7f29-4087-9b02-db3a29170223
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Profit1 = If(Orders[Profit]>=0,Orders[Profit],0)
		dataType: double
		lineageTag: 35cd7965-cbef-4a78-8278-0f9423ff201d
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Loss = if(Orders[Profit]<0,Orders[Profit],0)
		dataType: double
		lineageTag: efad1013-3ac6-4b48-8985-bf8a434e03e3
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Returns.Returned'
		dataType: string
		lineageTag: fb4a4d4f-cb22-419f-a053-f9b42dda3125
		summarizeBy: none
		sourceColumn: Returns.Returned

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Qtech\Downloads\Sample - Superstore (1).xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Merged Queries" = Table.NestedJoin(#"Promoted Headers", {"Order ID"}, Returns, {"Order ID"}, "Returns", JoinKind.LeftOuter),
				    #"Expanded Returns" = Table.ExpandTableColumn(#"Merged Queries", "Returns", {"Returned"}, {"Returns.Returned"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Returns","","No",Replacer.ReplaceValue,{"Row ID"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"No",Replacer.ReplaceValue,{"Row ID"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

